version: 0.0
os: linux
files:
  - source: /ROOT/*
    destination: /opt/lucee/tomcat/webapps/ROOT
hooks:
# Order is:
#  ApplicationStop
#  DownloadBundle
#  BeforeInstall
#  Install
#  AfterInstall
#  ApplicationStart
#  ValidateService

  ApplicationStop:
      - location: scripts/ApplicationStop.sh
        timeout: 300
        runas: root

  DownloadBundle:
      - location: scripts/DownloadBundle.sh
        timeout: 300
        runas: root

  BeforeInstall:
    - location: scripts/BeforeInstall.sh
      timeout: 300
      runas: root

  Install:
    - location: scripts/Install.sh
    timeout: 300
    runas: root

  AfterInstall:
    - location: scripts/AfterInstall.sh
    timeout: 300
    runas: root

  ApplicationStart:
    - location: scripts/ApplicationStart.sh
      timeout: 300
      runas: root

  ValidateService:
    - location: scripts/ValidateService.sh
      timeout: 300
      runas: root
